services:
  see-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: sse-node
    ports:
      - "3501:3501"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
